version: "3.10"

services:
  django:
    container_name: django
    build:
      dockerfile: aiogramBariev/Dockerfile
    command:
      - "python"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "python"
      - "bot.py"
      - "run"
  db:
    image: postgres:15
    container_name: db
    command: -p 5432
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER:?err}
      - POSTGRES_PASSWORD=${DB_PASS:?err}
      - POSTGRES_DB=${DB_NAME:?err}
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data

