# Generated by Django 5.0.6 on 2024-06-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiogramapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
