# Generated by Django 5.0.6 on 2024-06-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiogramapp', '0002_rename_description_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='aiogramapp.product')),
                ('tg_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aiogramapp.tguser')),
            ],
        ),
    ]
