# Generated by Django 5.0.6 on 2024-06-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiogramapp', '0003_tguser_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
