# Generated by Django 5.0.6 on 2024-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiogramapp', '0004_remove_product_count_basket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='tg_user',
        ),
        migrations.AddField(
            model_name='basket',
            name='tg_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
