# Generated by Django 5.0.6 on 2024-06-06 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiogramapp', '0006_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='tg_user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), blank=True, size=None),
        ),
    ]
