# Generated by Django 5.0.6 on 2024-06-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiogramapp', '0007_alter_newsletter_tg_user_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=1)),
                ('tg_id', models.BigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Totalcost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(default=1)),
                ('tg_id', models.BigIntegerField(default=1)),
            ],
        ),
    ]
